//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://tempuri.org/", ClrNamespace = "tempuri.org")]

namespace TSL.TAAA.Service.MsgWSDLService
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MsgObjectClass", Namespace = "http://tempuri.org/")]
    public partial class MsgObjectClass : object
    {

        private string Media_TypeField;

        private string System_IDField;

        private string SubjectField;

        private string MessageField;

        private string Dept_IDField;

        private string Employee_IDField;

        private string Content_TypeField;

        private string Content_FormatField;

        private string User_NoField;

        private string PriorityField;

        private string LiveTimeField;

        private TSL.TAAA.Service.MsgWSDLService.MsgObject[] MsgObjectField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Media_Type
        {
            get
            {
                return this.Media_TypeField;
            }
            set
            {
                this.Media_TypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string System_ID
        {
            get
            {
                return this.System_IDField;
            }
            set
            {
                this.System_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string Dept_ID
        {
            get
            {
                return this.Dept_IDField;
            }
            set
            {
                this.Dept_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string Employee_ID
        {
            get
            {
                return this.Employee_IDField;
            }
            set
            {
                this.Employee_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string Content_Type
        {
            get
            {
                return this.Content_TypeField;
            }
            set
            {
                this.Content_TypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string Content_Format
        {
            get
            {
                return this.Content_FormatField;
            }
            set
            {
                this.Content_FormatField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string User_No
        {
            get
            {
                return this.User_NoField;
            }
            set
            {
                this.User_NoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string LiveTime
        {
            get
            {
                return this.LiveTimeField;
            }
            set
            {
                this.LiveTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 11)]
        public TSL.TAAA.Service.MsgWSDLService.MsgObject[] MsgObject
        {
            get
            {
                return this.MsgObjectField;
            }
            set
            {
                this.MsgObjectField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MsgObject", Namespace = "http://tempuri.org/")]
    public partial class MsgObject : object
    {

        private string TargetField;

        private string Deliver_DateField;

        private string SubjectField;

        private string MessageField;

        private string Dept_IDField;

        private string Employee_IDField;

        private string Content_TypeField;

        private string POL_IDField;

        private string CLI_IDField;

        private string Branch_IDField;

        private string Agent_IDField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Target
        {
            get
            {
                return this.TargetField;
            }
            set
            {
                this.TargetField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string Deliver_Date
        {
            get
            {
                return this.Deliver_DateField;
            }
            set
            {
                this.Deliver_DateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string Dept_ID
        {
            get
            {
                return this.Dept_IDField;
            }
            set
            {
                this.Dept_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string Employee_ID
        {
            get
            {
                return this.Employee_IDField;
            }
            set
            {
                this.Employee_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string Content_Type
        {
            get
            {
                return this.Content_TypeField;
            }
            set
            {
                this.Content_TypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string POL_ID
        {
            get
            {
                return this.POL_IDField;
            }
            set
            {
                this.POL_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string CLI_ID
        {
            get
            {
                return this.CLI_IDField;
            }
            set
            {
                this.CLI_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string Branch_ID
        {
            get
            {
                return this.Branch_IDField;
            }
            set
            {
                this.Branch_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string Agent_ID
        {
            get
            {
                return this.Agent_IDField;
            }
            set
            {
                this.Agent_IDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SendMsgDataResultClass", Namespace = "http://tempuri.org/")]
    public partial class SendMsgDataResultClass : object
    {

        private int Status_CDField;

        private string Status_DescField;

        private string BatchIDField;

        private TSL.TAAA.Service.MsgWSDLService.SendMsgDataResult[] SendMsgDataResultField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int Status_CD
        {
            get
            {
                return this.Status_CDField;
            }
            set
            {
                this.Status_CDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Status_Desc
        {
            get
            {
                return this.Status_DescField;
            }
            set
            {
                this.Status_DescField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string BatchID
        {
            get
            {
                return this.BatchIDField;
            }
            set
            {
                this.BatchIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public TSL.TAAA.Service.MsgWSDLService.SendMsgDataResult[] SendMsgDataResult
        {
            get
            {
                return this.SendMsgDataResultField;
            }
            set
            {
                this.SendMsgDataResultField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SendMsgDataResult", Namespace = "http://tempuri.org/")]
    public partial class SendMsgDataResult : object
    {

        private int Status_CDField;

        private string Status_DescField;

        private string SerialField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int Status_CD
        {
            get
            {
                return this.Status_CDField;
            }
            set
            {
                this.Status_CDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Status_Desc
        {
            get
            {
                return this.Status_DescField;
            }
            set
            {
                this.Status_DescField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string Serial
        {
            get
            {
                return this.SerialField;
            }
            set
            {
                this.SerialField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SingleMsgObject", Namespace = "http://tempuri.org/")]
    public partial class SingleMsgObject : object
    {

        private string Media_TypeField;

        private string System_IDField;

        private string SubjectField;

        private string MessageField;

        private string Dept_IDField;

        private string Employee_IDField;

        private string Content_TypeField;

        private string User_NoField;

        private string PriorityField;

        private string LiveTimeField;

        private string TargetField;

        private string Deliver_DateField;

        private string POL_IDField;

        private string CLI_IDField;

        private string Branch_IDField;

        private string Agent_IDField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Media_Type
        {
            get
            {
                return this.Media_TypeField;
            }
            set
            {
                this.Media_TypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string System_ID
        {
            get
            {
                return this.System_IDField;
            }
            set
            {
                this.System_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string Dept_ID
        {
            get
            {
                return this.Dept_IDField;
            }
            set
            {
                this.Dept_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string Employee_ID
        {
            get
            {
                return this.Employee_IDField;
            }
            set
            {
                this.Employee_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string Content_Type
        {
            get
            {
                return this.Content_TypeField;
            }
            set
            {
                this.Content_TypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string User_No
        {
            get
            {
                return this.User_NoField;
            }
            set
            {
                this.User_NoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string LiveTime
        {
            get
            {
                return this.LiveTimeField;
            }
            set
            {
                this.LiveTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string Target
        {
            get
            {
                return this.TargetField;
            }
            set
            {
                this.TargetField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 11)]
        public string Deliver_Date
        {
            get
            {
                return this.Deliver_DateField;
            }
            set
            {
                this.Deliver_DateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 12)]
        public string POL_ID
        {
            get
            {
                return this.POL_IDField;
            }
            set
            {
                this.POL_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 13)]
        public string CLI_ID
        {
            get
            {
                return this.CLI_IDField;
            }
            set
            {
                this.CLI_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 14)]
        public string Branch_ID
        {
            get
            {
                return this.Branch_IDField;
            }
            set
            {
                this.Branch_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 15)]
        public string Agent_ID
        {
            get
            {
                return this.Agent_IDField;
            }
            set
            {
                this.Agent_IDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SingleMsgResultObject", Namespace = "http://tempuri.org/")]
    public partial class SingleMsgResultObject : object
    {

        private int Status_CDField;

        private string Status_DescField;

        private string BatchIDField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int Status_CD
        {
            get
            {
                return this.Status_CDField;
            }
            set
            {
                this.Status_CDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Status_Desc
        {
            get
            {
                return this.Status_DescField;
            }
            set
            {
                this.Status_DescField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string BatchID
        {
            get
            {
                return this.BatchIDField;
            }
            set
            {
                this.BatchIDField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "MsgServiceSoap")]
public interface MsgServiceSoap
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SetMessageData", ReplyAction = "*")]
    System.Threading.Tasks.Task<SetMessageDataResponse> SetMessageDataAsync(SetMessageDataRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SetSingleMsgData", ReplyAction = "*")]
    System.Threading.Tasks.Task<SetSingleMsgDataResponse> SetSingleMsgDataAsync(SetSingleMsgDataRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SetMessageDataRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "SetMessageData", Namespace = "http://tempuri.org/", Order = 0)]
    public SetMessageDataRequestBody Body;

    public SetMessageDataRequest()
    {
    }

    public SetMessageDataRequest(SetMessageDataRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class SetMessageDataRequestBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public TSL.TAAA.Service.MsgWSDLService.MsgObjectClass input;

    public SetMessageDataRequestBody()
    {
    }

    public SetMessageDataRequestBody(TSL.TAAA.Service.MsgWSDLService.MsgObjectClass input)
    {
        this.input = input;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SetMessageDataResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "SetMessageDataResponse", Namespace = "http://tempuri.org/", Order = 0)]
    public SetMessageDataResponseBody Body;

    public SetMessageDataResponse()
    {
    }

    public SetMessageDataResponse(SetMessageDataResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class SetMessageDataResponseBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public TSL.TAAA.Service.MsgWSDLService.SendMsgDataResultClass SetMessageDataResult;

    public SetMessageDataResponseBody()
    {
    }

    public SetMessageDataResponseBody(TSL.TAAA.Service.MsgWSDLService.SendMsgDataResultClass SetMessageDataResult)
    {
        this.SetMessageDataResult = SetMessageDataResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SetSingleMsgDataRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "SetSingleMsgData", Namespace = "http://tempuri.org/", Order = 0)]
    public SetSingleMsgDataRequestBody Body;

    public SetSingleMsgDataRequest()
    {
    }

    public SetSingleMsgDataRequest(SetSingleMsgDataRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class SetSingleMsgDataRequestBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public TSL.TAAA.Service.MsgWSDLService.SingleMsgObject input;

    public SetSingleMsgDataRequestBody()
    {
    }

    public SetSingleMsgDataRequestBody(TSL.TAAA.Service.MsgWSDLService.SingleMsgObject input)
    {
        this.input = input;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SetSingleMsgDataResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "SetSingleMsgDataResponse", Namespace = "http://tempuri.org/", Order = 0)]
    public SetSingleMsgDataResponseBody Body;

    public SetSingleMsgDataResponse()
    {
    }

    public SetSingleMsgDataResponse(SetSingleMsgDataResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class SetSingleMsgDataResponseBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public TSL.TAAA.Service.MsgWSDLService.SingleMsgResultObject SetSingleMsgDataResult;

    public SetSingleMsgDataResponseBody()
    {
    }

    public SetSingleMsgDataResponseBody(TSL.TAAA.Service.MsgWSDLService.SingleMsgResultObject SetSingleMsgDataResult)
    {
        this.SetSingleMsgDataResult = SetSingleMsgDataResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
public interface MsgServiceSoapChannel : MsgServiceSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
public partial class MsgServiceSoapClient : System.ServiceModel.ClientBase<MsgServiceSoap>, MsgServiceSoap
{

    /// <summary>
    /// 實作此部分方法來設定服務端點。
    /// </summary>
    /// <param name="serviceEndpoint">要設定的端點</param>
    /// <param name="clientCredentials">用戶端認證</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

    public MsgServiceSoapClient(EndpointConfiguration endpointConfiguration) :
            base(MsgServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), MsgServiceSoapClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public MsgServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
            base(MsgServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public MsgServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
            base(MsgServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public MsgServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SetMessageDataResponse> MsgServiceSoap.SetMessageDataAsync(SetMessageDataRequest request)
    {
        return base.Channel.SetMessageDataAsync(request);
    }

    public System.Threading.Tasks.Task<SetMessageDataResponse> SetMessageDataAsync(TSL.TAAA.Service.MsgWSDLService.MsgObjectClass input)
    {
        SetMessageDataRequest inValue = new SetMessageDataRequest();
        inValue.Body = new SetMessageDataRequestBody();
        inValue.Body.input = input;
        return ((MsgServiceSoap)(this)).SetMessageDataAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SetSingleMsgDataResponse> MsgServiceSoap.SetSingleMsgDataAsync(SetSingleMsgDataRequest request)
    {
        return base.Channel.SetSingleMsgDataAsync(request);
    }

    public System.Threading.Tasks.Task<SetSingleMsgDataResponse> SetSingleMsgDataAsync(TSL.TAAA.Service.MsgWSDLService.SingleMsgObject input)
    {
        SetSingleMsgDataRequest inValue = new SetSingleMsgDataRequest();
        inValue.Body = new SetSingleMsgDataRequestBody();
        inValue.Body.input = input;
        return ((MsgServiceSoap)(this)).SetSingleMsgDataAsync(inValue);
    }

    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }

    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.MsgServiceSoap))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        if ((endpointConfiguration == EndpointConfiguration.MsgServiceSoap12))
        {
            System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
            System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
            textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
            result.Elements.Add(textBindingElement);
            System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
            httpBindingElement.AllowCookies = true;
            httpBindingElement.MaxBufferSize = int.MaxValue;
            httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
            result.Elements.Add(httpBindingElement);
            return result;
        }
        throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
    }

    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.MsgServiceSoap))
        {
            return new System.ServiceModel.EndpointAddress("http://potsap02/TMSG/MsgService.asmx");
        }
        if ((endpointConfiguration == EndpointConfiguration.MsgServiceSoap12))
        {
            return new System.ServiceModel.EndpointAddress("http://potsap02/TMSG/MsgService.asmx");
        }
        throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
    }

    public enum EndpointConfiguration
    {

        MsgServiceSoap,

        MsgServiceSoap12,
    }
}
